version: "3"
services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm run serve
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: >
      sh -c "mysql -h 127.0.0.1 -u root -pexample Devtool.sql < /docker-entrypoint-initdb.d/Devtool.sql"
volumes:
  db-data:
